version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgis_db
    environment:
      POSTGRES_DB: mzz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mzz
      - GIN_MODE=debug
      - PORT=80
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data: